name: Deploy to GitHub Pages
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo  "${{ secrets.FIREBASECONFIG }}" > config.json
      - uses: actions/upload-artifact@v3
        with:
          name: config
          path: config.json