name: Deploy to GitHub Pages
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo  "${{ secrets.FIREBASECONFIG }}" > config.json
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: .
